Update edit_repo_pr_auto.yml

diff --git a/.github/workflows/edit_repo_pr_auto.yml b/.github/workflows/edit_repo_pr_auto.yml
--- a/.github/workflows/edit_repo_pr_auto.yml
+++ b/.github/workflows/edit_repo_pr_auto.yml
@@ -44,7 +44,7 @@ jobs:
                 break
               fi
           done
-          (( $BACKOFF )) || echo "Could not create the PR" && false
+          (( $BACKOFF )) || ( echo "Could not create the PR" && false )
           # gh pr create returns before the pr is ready, we have to poll until success
           # https://github.com/cli/cli/issues/2619#issuecomment-1240543096        
           for BACKOFF in 1 2 4 8 15 15 15 15 0; do
@@ -54,4 +54,4 @@ jobs:
                   break
               fi
           done
-          (( $BACKOFF )) || echo "Could not set automerge" && false
+          (( $BACKOFF )) || ( echo "Could not set automerge" && false )
